name: CrystalQuest
main: nl.sugcube.crystalquest.CrystalQuest
version: 1.3.1
authors: [SugarCaney]
softdepend: [Multiverse-Core]
description: >
             The battle for the crystals!
commands:
  cq:
    description: Main command of CrystalQuest-plugin.